services:
  backend:
      build: 
        context: ./backend
      container_name: manga-backend
      depends_on:
          mysql:
              condition: service_healthy
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pessoal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      networks:
        - manga-network
      restart: always